Python中有Numpy,深度学习框架比Numpy的ndarray多一些重要功能：首先，GPU很好地支持加速计算，而Numpy仅支持CPU计算；其次，张量类支持自动微分。

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [6]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.randn(3,4)

tensor([[-0.2122, -0.3771, -0.5219, -0.4192],
        [ 3.0424,  0.8431,  0.0709,  0.4252],
        [ 0.4733,  1.1451, -0.4042, -0.3105]])

# 广播机制
通过适当复制元素来扩展一个或两个数组



In [9]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [10]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

# 节省内存

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [13]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print("id(Z):", id(Z))

id(Z): 4409553840
id(Z): 4409553840


In [14]:
X < Y 

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [24]:
Q = torch.tensor([10, 20]).reshape(1, 1, 2)  
Q

tensor([[[10, 20]]])

In [22]:
P = torch.arange(8).reshape((2,2,2))
P

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [25]:
Q + P 

tensor([[[10, 21],
         [12, 23]],

        [[14, 25],
         [16, 27]]])