## 张量算法的基本性质

In [2]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone() # 通过分配新内存， 将A的一个副本分配给B
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

## 降维

In [3]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

以矩阵为例，为了通过求和所有行元素来降维（轴0），可以在调用函数时，指定axis=0。压缩行，理解为向上压缩，直至只存在一行。压缩列，理解为向左压缩，直至只存在一列。

## 非降维求和

保持总轴数不变会很有用。

## 点积

torch.dot

## 矩阵乘法

torch.mm(A,B)

## 范数

L2范数时向量的平方之和求根    
L1范数时向量的绝对值之和